liip_imagine:
    twig:
        mode: lazy
    filter_sets:
        user_avatar:
            jpeg_quality:          85
            png_compression_level: 8

            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [128, 128]
                    mode:          outbound
                    allow_upscale: true

        user_avatar_512:
            jpeg_quality:          85
            png_compression_level: 8

            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [512, 512]
                    mode:          outbound
                    allow_upscale: true

        portfolio_440:
            jpeg_quality: 85
            png_compression_level: 8

            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size: [ 440, 290 ]
                    mode: outbound
                    allow_upscale: true