liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    twig:
        mode: lazy

    filter_sets:
        cache: ~

        editor_preview:
            filters:
                thumbnail:
                    size: [ 600, 600 ]
                    mode: inset
                strip: ~
            quality: 82

        user_avatar:
            jpeg_quality:          85
            png_compression_level: 8

            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [128, 128]
                    mode:          outbound
                    allow_upscale: true

        user_avatar_512:
            jpeg_quality:          85
            png_compression_level: 8

            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [512, 512]
                    mode:          outbound
                    allow_upscale: true

        portfolio_440:
            jpeg_quality: 85
            png_compression_level: 8

            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size: [ 440, 290 ]
                    mode: outbound
                    allow_upscale: true

        blog_780:
            jpeg_quality: 85
            png_compression_level: 8

            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size: [ 780, 550 ]
                    mode: outbound
                    allow_upscale: true
        blog_1920:
            jpeg_quality: 80
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size: [ 1920, 950 ]
                    mode: outbound
                    allow_upscale: true

        reference_thumb:
            jpeg_quality: 85
            png_compression_level: 8
            # if your logos have transparency, keep PNG output:
            # format: png

            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size: [ 100, 35 ]      # max width x max height
                    mode: inset          # ⟵ keep aspect ratio, no crop
                    allow_upscale: false # avoid enlarging tiny logos