twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    file_name_pattern: '*.twig'

    globals:
        ga_tracking_id: '%ga_tracking_id%'
        friendly_container_id: '%friendly_container_id%'

when@test:
    twig:
        strict_variables: true
