vich_uploader:
    db_driver: orm

    mappings:
        media_images:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
        avatars:
            uri_prefix: /media/users
            upload_destination: '%kernel.project_dir%/public/media/users'
            namer: App\Controller\Upload\Namer\UniqueIdFileNamer
        portfolios:
            uri_prefix: /media/portfolios
            upload_destination: '%kernel.project_dir%/public/media/portfolios'
            namer: App\Controller\Upload\Namer\UniqueIdFileNamer
        references:
            uri_prefix: /media/references
            upload_destination: '%kernel.project_dir%/public/media/references'
            namer: App\Controller\Upload\Namer\UniqueIdFileNamer
        blogs:
            uri_prefix: /media/blogs
            upload_destination: '%kernel.project_dir%/public/media/blogs'
            namer: App\Controller\Upload\Namer\UniqueIdFileNamer