webpack_encore:
    # The path where Encore is building the assets for the default (admin) build
    output_path: '%kernel.project_dir%/public/assets'

    # Register the additional frontend build
    builds:
        front: '%kernel.project_dir%/public/assets-front'

    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: false
        # Uncomment (also under link_attributes) if using Turbo Drive
        # https://turbo.hotwired.dev/handbook/drive#reloading-when-assets-change
        # 'data-turbo-track': reload
    # link_attributes:
        # Uncomment if using Turbo Drive
        # 'data-turbo-track': reload

    # If using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'

    # Preload all rendered script and link tags automatically via the HTTP/2 Link header
    # preload: true

    # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    # strict_mode: false

when@prod:
    webpack_encore:
        # Use the same directories as development, but with caching enabled
        cache: true

#when@test:
#    webpack_encore:
#        strict_mode: false
