# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'de'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: de
    app.notifications.email_sender: petersacco@websitemaster.ch
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    google_recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
    ga_tracking_id: '%env(GA_TRACKING_ID)%'
    friendly_container_id: '%env(FRIENDLY_CONTAINER_ID)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file / autowiring
            string $locales: '%app_locales%'
            string $defaultLocale: '%locale%'
            string $emailSender: '%app.notifications.email_sender%'
            string $uploadsPath: '%kernel.project_dir%/public/media'
            string $imagesPath: '%kernel.project_dir%/public/assets/images'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\AuthManager:
        public: true

    App\Service\FileUploader:
        arguments:
            $vichConfig: '%vich_uploader.mappings%'

    Pyrrah\GravatarBundle\GravatarApi:
        alias: gravatar.api

    Symfony\Component\Security\Http\Logout\LogoutUrlGenerator: '@security.logout_url_generator'

    App\Controller\Auth\RegistrationController:
        arguments:
            $googleRecaptchaSiteKey: '%google_recaptcha_site_key%'
            $registrationLimiterFactory: '@limiter.registration_limit'

    Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator:
        alias: 'security.authenticator.form_login.main'

    App\Controller\Upload\Namer\UniqueIdFileNamer:
        public: true
        tags:
            - { name: vich_uploader.namer, alias: namer }

    App\Twig\TrackingExtension:
        arguments:
            $pixels: '%tracking.pixels%'
        tags:
            - { name: twig.extension }